import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/shared/header";
import "@fortawesome/fontawesome-free/css/all.min.css"
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Row, Col } from "antd";
import Sidebar from "@/components/shared/sidebar/sidebar";
import MainLayout from "./main_layout";
import 'rc-slider/assets/index.css';
import { PlaybarProvider } from "@/context/playbar-context";
import { UserProvider } from "@/context/user-context";
import { SidebarProvider } from "@/context/sidebar-context";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { QueuebarProvider } from "@/context/queuebar-context";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <body>

          <AntdRegistry>
            <UserProvider>
              <PlaybarProvider>
                <QueuebarProvider>
                  <SidebarProvider>
                    <MainLayout>
                      {children}
                      <ToastContainer
                        position="bottom-center"
                        autoClose={1200}
                        hideProgressBar={false}
                        newestOnTop={false}
                        closeOnClick
                        rtl={false}
                        pauseOnFocusLoss
                        draggable
                        pauseOnHover
                        theme="dark"
                      />
                    </MainLayout>
                  </SidebarProvider>
                </QueuebarProvider>
              </PlaybarProvider>
            </UserProvider>
          </AntdRegistry>


        </body>


      </body>
    </html>
  );
}
