import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/shared/header";
import "@fortawesome/fontawesome-free/css/all.min.css"
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Row, Col } from "antd";
import Sidebar from "@/components/shared/sidebar/sidebar";
import MainLayout from "./main_layout";
import 'rc-slider/assets/index.css';
import { PlaybarProvider } from "@/context/playbar-context";
import { UserProvider } from "@/context/user-context";
import { SidebarProvider } from "@/context/sidebar-context";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <body>

          <AntdRegistry>
            <UserProvider>
              <PlaybarProvider>
                <SidebarProvider>
                  <MainLayout>{children}</MainLayout>
                </SidebarProvider>
              </PlaybarProvider>
            </UserProvider>
          </AntdRegistry>


        </body>


      </body>
    </html>
  );
}
